### ISSUE TITLE
エンドユーザー向けのサイトのタイトル再考

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection#11]
プロジェクト名としては Code for 選挙でも良いと思うのですが、エンドユーザーが使うサイトについては、もう少しわかりやすい名前の方が良いかもと思いました。
とはいえ、「2017衆院選候補者データベース」とかだと硬すぎるし、何かいいサービス名ないですかね。
TheyWorkForYou ってのは個人的には好きなんだけども。
「候補者ナビ」だと、dotjp の政治naviと被るか。なんかいいアイデアないですかねー

**Comment by tomoaki-n** [comment]
「閻魔帳」とかいかがでしょう

**Comment by hkwi** [comment]
「選挙Q」QはクエリのQ とか（適当）

**Comment by halsk** [comment]
codeforelection_front 側のIssueに移行
