### ISSUE TITLE
mySociety 側に質問したいこと

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection#14]
みなさん、mySociety 側に確認したいことがあればこちらに書き込んでください。まとめて先方に聞きます。
現在、まずは今回彼らが考えていることの技術的な詳細を送ってもらう予定ですので、それを待ってからでも良いかもですが。（おそらく返答は週明け）

**Comment by tetsuyas1** [comment]
## mySocietyから提供されたテーブルの埋め方について
- https://docs.google.com/a/mysociety.org/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit?usp=sharing

### そもそも現状の整理
- （わかってないの私だけかもしれませんが汗）
- A)seijinaviから取得されたデータ
- B)wikidataに登録すべきデータ
- C)popoloに登録すべきデータ
- D) mySocietyテーブル（English）


### 対応してる方針
- データのリッチさからしてC>Bなので、Cの内容を埋める？
- C=>Dへは翻訳（ローマ字化）作業が必要？
- A=>Cについては、いま東さんがコツコツと作業してる？

ちょっと理解しているのはこんなところなのですが、捕捉あればお願いします。

**Comment by nyampire** [comment]
僕もちょっと混乱してきたので、まとめてみました。
こんなかんじだと理解しています。

スレッドの中身と話題が違うので、長くなりそうな場合はスレッド変えたほうがよさそうですね。

## いまあるデータベースと、必要な作業
A)seijinaviから取得されたデータ: 生Dump。現在の政治家リスト
B)[wikidataに登録すべきデータ](https://docs.google.com/spreadsheets/d/1T6BhIk_TU9KAOmBou8buvMkj_yK4c72jcJMGMOFUAg0/edit#gid=0): Aから抽出した、立候補者となる可能性が高いリスト。
C)[立候補者一覧。Code for 選挙として登録すべきデータ(popolo形式で作成する)](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=0):  現状はGrayDBとして呼称。公示日後に候補者確定した後に抽出して別DBになる？
D)[mySocietyテーブル（English）](https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit#gid=514555971): 英語で入力必要。当選者のみの入力を行う。EveryPolitician用データ。
E)[Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)

実施している作業としては。
* 現在、政治ナビからいただいたデータを調査に依って補完しつつ、Wikidataに登録する作業が行われています。
* 立候補者の一覧の入手（Cの確定に必要）を行っています。

**Comment by hkwi** [comment]
データ

- A 政治ナビさんデータ (google docs)
- B GrayDB (google docs)
- C wikidata (wikidata)
- D codeforelection_front DB (json?)
- E codeforelection popolo JSON (popolo json)
- F EveryPolitician Sheet (google docs)

それぞれこんな感じかと。

- wikidata で ID を採番したい
- A=>C は出典がはっきりしているし、情報が揃っているので、コツコツ作業中。確度高め。
- B にデータを集めて行く。wikidata Q ID や A もマージする。
  - A のマージは未実施。wikidata Q ID 揃ってからマージしようかと
- C にはすべてのデータは今のところ入りきらない
  - 選挙用に使っている名前の表記方法
  - 年齢（誕生日が必要）
  - 当選回数
- D は要件待ち？
- E は開票後
  - 候補者の段階でも一度 出力してみてもいいけれど、もともと選挙向けではないので工夫が必要。
- F は範囲が広すぎるので、A-E の成果物から出せるところは協力する、というスタンスで良いかと。
  - 衆議院立候補者一覧
  - 参議院議員一覧
  - 首長一覧

Links:

- A: https://docs.google.com/spreadsheets/d/1T6BhIk_TU9KAOmBou8buvMkj_yK4c72jcJMGMOFUAg0/edit
- B: https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit
- C: https://wikidata.org/
- D: election_front のどこかに置く感じ？
- E: election のどこかに生成して置く感じ？
- F: https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit

**Comment by nyampire** [comment]
投稿がかぶったｗ @hkwiさんのほうがまとまってるので、混乱避けるために僕の方消しますね。

**Comment by nyampire** [comment]
![2017-10-05 18 10 46](https://user-images.githubusercontent.com/428218/31219521-907d82ca-a9f8-11e7-940b-64356290a1b9.png)

図にしてみた。とりあえず、Wikidataへの登録と、政治ナビデータへのWikidataID付与、それからGrayDBへのマージまでを最初にやる、ということで考えてますが、他にあるかな？

**Comment by nyampire** [comment]
mySocietyとのミーティングメモはこちら。

* https://hackmd.io/MYRhGYFYDME5oLQDZpKQgLBpATBBDYADnQHZTh8AjacEaI0ooA==#

作業フローについては #34 で別途話しましょう。

**Comment by nyampire** [comment]
いったん落ち着いているのと、slackで直にやり取りするようになっているのでこちらクローズ
