### ISSUE TITLE
方向性を決めるオンラインミーティング開催

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#16]
10.2 月曜日あたりで

**Comment by rish314** [comment]
19時以降なら参加可能です！

**Comment by tetsuyas1** [comment]
明日の２１時から可能な方でオンラインMTGするのはどうでしょうか。

**Comment by halsk** [comment]
+1

**Comment by halsk** [comment]
遅くて恐縮ですが、21時からでお願いしたいです！

**Comment by nyampire** [comment]
開催を行いました。議事録は[こちら](https://hackmd.io/EbDMGMDMEMBMEYC0lZUQFgByVIzBWaSRcadeSABngHZwA2ATgCYg?view)。
