### ISSUE TITLE
データとサイトとコードの利用規約を設定する

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#17]
サイトの内容が、3つの階層（データ・サイトの文言と表現・コード）に分かれているので、それぞれに対してライセンスを設定する。

また、権利保持主体はCode for Japanが代表する形でよいか？

以下、決めることとその内容の案。

- [x] コードのライセンス設定：MITライセンス？
- [x] データのライセンス設定：CC0でよい？
- [x] サイトの文言と表現のライセンス設定：CC-BY？こちらもCC0？

- [x] コードのライセンスを明示する
- [x] データのライセンスを明示する
- [x] サイトの文言と表現のライセンスを明示する

**Comment by nyampire** [comment]
フロントエンドについては別リポジトリだった。
と、いうわけで、そちらはMITであることが確認できたのでその部分完了。

https://github.com/codeforjapan/codeforelection_front

**Comment by halsk** [comment]
データのライセンス設定：CC0
 サイトの文言と表現のライセンス設定：CC-BY
がよいのではないかと思いますが、他の皆さん懸念事項ありますか？

**Comment by nyampire** [comment]
異論なさそうなので、READMEに追記しちゃいますね。

**Comment by nyampire** [comment]
フロントのほうにも追記しました

https://github.com/codeforjapan/codeforelection_front/pull/13
