### ISSUE TITLE
Popolo形式のチュートリアルのリンク先共有

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#21]
プロジェクト内の開発者が学ぶための資料を誰か提示してください。

**Comment by koujikozaki** [comment]
とりあえず
http://www.popoloproject.com/
にクラスやプロパティの一覧が掲載されており，Serializationの項目には，サンプルデータもあります．
あと
https://github.com/everypolitician
にeverypoliticianで作ってるツール類がいろいろあります．

**Comment by hkwi** [comment]
メモを書きました。https://qiita.com/kwi/items/e689a9a94ad8a7780b5d

popolo 形式は複数のプロジェクトで活用されていて、[OpenCivicData](http://docs.opencivicdata.org/en/latest/) も参考になります。

EveryPolitician で配布されているもので言えば、[Download](http://everypolitician.org/japan/house-of-representatives/download.html) ページの JSON が popolo の [Database](http://www.popoloproject.com/appendices/components.html#interoperability) に対応しているようです。

仕様についての議論は [github 上](https://github.com/popolo-project/popolo-spec/issues) にあります。

**Comment by halsk** [comment]
Wiki の方に[Popoloについてのページ](https://github.com/codeforjapan/codeforelection/wiki/Popolo%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)を作ったので、こちらclose します。
