### ISSUE TITLE
メンバーやサポーターの記述

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection#26]
開発メンバーや、データ提供元なども記載したい（ここに dotjp さんとかも記述）

**Comment by nyampire** [comment]
READMEの項目ではなくて、別途ファイルつくるほうがよいです？

**Comment by nyampire** [comment]
クラウドソーシングとしてやれることが決まってきたら、How to Contributeのドキュメントつくって、そこに格納するようにします。

**Comment by hkwi** [comment]
https://docs.google.com/spreadsheets/d/1T6BhIk_TU9KAOmBou8buvMkj_yK4c72jcJMGMOFUAg0/edit#gid=0 これを wikidata に登録するの、手伝っていただけるとありがたいですー！

**Comment by higa4** [comment]
上記シートに書き込み権限が無いのですが、登録済みの印はどう付けたら良いでしょうか

**Comment by hkwi** [comment]
すみません…単純に設定ミスってました。（確認したつもりが edit 権開放できてませんでした…）

フィールドなど適宜追加して頂けるとありがたく。

**Comment by higa4** [comment]
了解ですー。ありがとうございます。

**Comment by nyampire** [comment]
HowToContributeを書いてみました。もうちょっと追記しても良いと思うので、適宜追加してゆくかんじで。

#30 
https://github.com/codeforjapan/codeforelection/blob/master/HowToContribute.md

**Comment by halsk** [comment]
ありがとうございます！拡散しました。
上記Spreadsheetへの導線は作らない感じですか？
また、現在◯%完了！とかあるとテンション上がるかも

**Comment by nyampire** [comment]
wikidataの解説のページから辿ったほうがよいな、と思ったのですが、先にSpreadsheetへのリンクがあったほうがわかりよさそうですね。そうします。

あと、spreadsheetの最初のところに、完了した数の関数いれてみました。現在約15％完了。

**Comment by nyampire** [comment]
追記してみました。

**Comment by yokinist** [comment]
質問させてください！

> twitter,facebook,ホームページを入れて行って頂けると助かります。他はだいたい入っていますが生年月日が年までしか入っていないものがあります。10/5 higa4
[現在の議員リスト](https://docs.google.com/spreadsheets/d/1T6BhIk_TU9KAOmBou8buvMkj_yK4c72jcJMGMOFUAg0/edit#gid=0)

とのことですが、Wikidataへ登録するのはある程度データが埋まってから始めるという認識で問題ないですか？

**Comment by higa4** [comment]
遅くなりました。上記リストは「政治ナビより贈り物」ということでウィキデータに入力しても良いものとしてもらったものですので、このリストを充実させる必要は無く、これを見てすぐにウィキデータへの転記を進めて頂いて問題ありません。お手伝い頂けると大変助かります。

**Comment by yokinist** [comment]
@higa4 
承知しました。ありがとうございます！

**Comment by higa4** [comment]
こちらこそ、よろしくお願いします！

**Comment by nyampire** [comment]
こちら、本来の目的は達成されたと思いますので、クローズします
