### ISSUE TITLE
Wikidataの操作説明書を作る

### ISSUE THREAD

**Issue by higa4** [codeforjapan/codeforelection#27]
下記に作りつつあります。
https://hackmd.io/BzDGE4FMAYGYDMC0AjYBWNiAs9m0ePKJCgExQDsAjACZXizgVA==
広く呼びかける前提なので少し前置きがくどくなってしまいました。。

**Comment by hkwi** [comment]
https://www.wikidata.org/wiki/Help:Sources/ja へのリンクをどこかに潜ませて頂けるとありがたく。

**Comment by higa4** [comment]
ご指摘ありがとうございます。情報源へのリンクを3.2.1から張りました。
いちおう初版としてはだいたい書いたつもりです。お気づきの点は直接修正いただいてもかまいませんのでよろしくお願いします。
あとは@hkwiさんが作ってくれた立候補者グレイリストにウィキデータへの登録作業欄を作って、そこで作業中のものを宣言（担当者、記入日付、完了予定日付くらいを入力？）してもらいながら排他制御できると進捗も見えて良いかなと思います。

**Comment by nyampire** [comment]
文書作成ありがとうございます。（wikidata登録してみました）

この文書をどこからリンクしようかと思っているのですが、
例えば、HOW_TO_CONTRIBUTE.mdのようなドキュメントを作って、そこからリンクすることを考えています。同じ文書に、コントリビュータとデータ提供者のリストを作るイメージ。

https://github.com/codeforjapan/codeforelection/issues/26

**Comment by higa4** [comment]
はい。ご自由にドゾー。文書は時々更新します。

**Comment by halsk** [comment]
マニュアル完成しているので終了
