### ISSUE TITLE
9日のもくもく会の会場とロジを決める

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#28]
9日にもくもく作業日を設定するとして、場所と時間を決める。

**Comment by nyampire** [comment]
場所の候補。時間は、各自でランチの後、13:00−18:00くらいを目途？

1 SENQ霞が関（ロビー）
* メリット：Georepublicのあるところなので利用が気楽。ロビーであれば無料。人通りはある。
* デメリット：15人を超えてくると大変かも。

2 Code for Japanオフィス＠本郷
* メリット：外部のひとがいない。食事しながら作業できる
* デメリット：ちょっとだけ狭い （最大10人くらい？）

3 Yahoo! Japan LODGEの一角＠永田町
* メリット：場所が永田町（！）。いろんなひとがいる。
* デメリット：休日なので軽食コーナーはおやすみ。場所取りが大変かも？（休日＆イベント無しの日なので大丈夫だと思う）

**Comment by nyampire** [comment]
もくもく会のFacebookイベントページは[こちら](https://www.facebook.com/events/1543590639037317/?acontext=%7B%22ref%22%3A%224%22%2C%22feed_story_type%22%3A%22370%22%2C%22action_history%22%3A%22null%22%7D)。

イベントページだと11:00から。

**Comment by nyampire** [comment]
11:00から開始した場合のスケジュール案。チームに分けてもくもくする感じ。

11:00 集合
11:05 現状とタスク概要の確認、チーム分け。初回参加組は追加でレクチャー必要かも。
11:20 チームごとに詳細インストラクション
12:00 休憩＆ランチ（ピザとか頼む？）
13:00 適宜、作業再開
17:00 デプロイの儀（？）
17:30 次タスクの確認
18:00 撤収

**Comment by nyampire** [comment]
場所的にはどこでも大きく違和感ないとおもうので、5日夕方くらいまで意見を待って、そこでエイヤっと決めちゃおうかと思っています。（SENQ霞が関かLODGEがいいかな、という印象）

**Comment by yoshimaru7** [comment]
場所の案内や使い勝手考えると本郷はイマイチなので（過去辿り着けずに迷う人多数）、同じくSENQかLODGEがいいかなと思いますー（僕はお茶のみメインですけど

**Comment by higa4** [comment]
SENQはその日（休日）使えるかどうか、無料かどうかは確認したほうが良いかもです。

**Comment by nyampire** [comment]
はい、それを明日確認して確定かなー、と思っていました＞SENQ

**Comment by halsk** [comment]
SENQは祝日は空調効かないそうなので、本郷のCfJオフィスかな。人数がどれくらいかにもよりますが。

**Comment by halsk** [comment]
まずはLODGE確認してみますか。

**Comment by nyampire** [comment]
SENQは僕も確認したのですが、共有部分は平日のみみたいですね。

LODGEは、普通に使うには問題なさそうです。（イベントも無いみたい）
Code for JapanとしてPJルームの場所の予約までするかどうか、というところですが、そこまでは要らないかなぁ、と思っています。どうでしょう？

https://lodge.yahoo.co.jp/event_pc.html

**Comment by nyampire** [comment]
念の為LODGEに、利用可能かどうか問い合わせ中。

**Comment by nyampire** [comment]
LODGEから回答あり。9日は利用可能とのこと。

10人程度であれば、[PJルーム](https://reserva.be/lodge)の利用を推奨。ただし上限は2hまで。

11:00-12:00の間のチーム分け、それから12:00−13:00のランチあたりをPJルームで行って、その後はチームごとにテーブルにわかれて作業すればまとまりそうです。

**Comment by halsk** [comment]
10人くらいならLODGEより本郷CfJオフィスの方が良く無いですか？場所わかりにくいのは、なんとかなるでしょう。

**Comment by nyampire** [comment]
僕としてはどちらでもよいです。いまFacebookの参加者数が10名弱。まずは本郷でやりましょうか。

Facebookのイベントページ（と、プロジェクト参加者に名前があるひとへのメール連絡）でもっと参加者が増えて20を超えるくらいになってきたら、LODGEに変更を検討、ということで。
変更検討のジャッジタイミングを土曜日くらいにすれば、告知もなんとかなるはず。

と、いうわけで、9日は本郷CfJオフィスに11:00から、ということで告知文章考えます。

http://www.code4japan.org/aboutus/

**Comment by nyampire** [comment]
ひとまずFBのイベントページを文言修正して、CfJ参加者ページに共有しましたん。
プロジェクトに参加表明されているかたにメールしようかと思ったけど、メアドまでは書いてないのでペンディング。
（名前しかわからないって、なんか血判状ぽくてひとりでウケてた）

**Comment by nyampire** [comment]
告知も終わったのでクローズ

**Comment by nyampire** [comment]
遠隔のひとがそれなりの数いる気がするので、配信設備を整える必要があることに気が付きました。

- [ ] マイクとカメラを用意する
- [ ] 配信用のMtg roomを作る（Zoomとかそういうやつ）

**Comment by yokinist** [comment]
@nyampire

イベントページの文言について提案があります
https://www.facebook.com/events/1543590639037317/

> Code for Japan 参加メンバー向けグループのイベント

と表記されている関係で「CfJのメンバーじゃない人でも参加できるか」という質問がありました。
下記のようによくある質問に追加していただけると、わかりやすいかと思います！

```
* よくある質問
Q. CfJのメンバーじゃない人でも参加できますか？
A. もちろん大歓迎です。興味ある方でしたら誰でも参加可能です！
```

お時間ある時で構わないので、よろしくお願いします！

**Comment by nyampire** [comment]
@ikt2y ありがとうございます、反映しましたー
