### ISSUE TITLE
議事録も参照できるようにする？

### ISSUE THREAD

**Issue by hkwi** [codeforjapan/codeforelection#29]
その議員が過去何を発言していたかを検索できると嬉しい。

ただデータソースが [こんな感じ](http://www.shugiin.go.jp/internet/itdb_kaigiroku.nsf/html/kaigiroku/000119320170616035.htm) なので、どうしたものか。

**Comment by halsk** [comment]
こういうAPIがあるのですが、発言者で引っ張ってきて表示できないですかね。
http://kokkai.ndl.go.jp/api.html
2017年10月4日(水) 14:08 Hiroaki KAWAI <notifications@github.com>:

**Comment by hkwi** [comment]
いいですね。見てみたのですが kokkai.ndl.go.jp の API は CORS ヘッダである Access-Control-Allow-Origin 返してくれないのですね。なのでフロント JavaScript のみでの実装は難しそう。大量アクセスが出ると困りますし、対応方法はいくつか考えられますが、 HTML でいくなら、いずれにせよフロントからは別途準備したサーバから返さないとダメな感じですね。アプリならそのままでも大丈夫かも。

（API で返ってくるデータを dump して使ってもいいんだろうか…？）

**Comment by halsk** [comment]
いずれにせよサーバ立てるので、サーバサイドで処理しませう

**Comment by ypresto** [comment]
oO（このAPI、クエリ文字列の区切りの `&` も `%26` にURLエンコードしないといけないんですね・・ｗ）

**Comment by halsk** [comment]
こちらに移動させました。
https://github.com/codeforjapan/codeforelection_front/issues/147
