### ISSUE TITLE
【郵便番号-小選挙区照合データ】複数の小選挙区に分割される基礎自治体について、町字から選挙区を割り出せる仕組みを作る

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#3]
# 想定されている手順
- 入力された郵便番号から、基礎自治体コードを引く
- city2senkyoku.jsonを使って、当該基礎自治体コードが複数小選挙区自治体かどうか確認
- 複数小選挙区自治体でない場合は、選挙区を返す
- 複数小選挙区自治体の場合は、町字から選挙区を推定する　<=このイシューではこれを作成する。

**Comment by yoshimaru7** [comment]
同じ郵便番号でも異なる選挙区があるという情報を得ました（下記は一例で、他にもあるようです）。
問題ありませんか？

港区海岸３丁目は
第１区が、４番から１３番まで、２０番、２１番及び３１番から３３番まで
第２区が、１番から３番まで、１４番から１９番まで及び２２番から３０番まで
となっていて、郵便番号も同じ（108-0022）

**Comment by tetsuyas1** [comment]
承知しました。
対応が困難ですので、例外として注記しておきたいと思います。

**Comment by yoshimaru7** [comment]
了解です。全般まとめて一言注記で済ませますか？それとも同様のケースの一覧があるとベターですか？

**Comment by yoshimaru7** [comment]
備忘録として入れておきます。今回の選挙区割りの一覧。
http://www.soumu.go.jp/senkyo/senkyo_s/news/senkyo/shu_kuwari/
これがデータ構造をなしてない事が諸悪の根源で、これ何とかする所から手を付けないと、やばい気がしてきた。（というのを、Code for Japanで出来ないのかな）

**Comment by halsk** [comment]
例外注記を書くということになったので、再Closeします。

**Comment by akiranszw** [comment]
選挙区のポリゴンデータを作成した西沢です。２選挙区に分かれる町域（丁目単位で異なる、あるいは、１つの丁目が分割されている）をチェックしました。その中には町域が２つの郵便番号に分かれるものも見つかりました。チェックにはポリゴン作成時に作成した２選挙区に分割された町丁字リストと、町丁字と選挙区の対応表から丁目により異なる選挙区になっている町域を機械的に抽出した結果を利用しました。この他に同じ名前の大字と丁目の町域がある場合に、大字と丁目で選挙区が異なる可能性もありますが、コード番号で照合できないので、このケースは分かっていた範囲の１箇所だけ抽出しました。これらを反映して、postal2senkyoku.jsonを修正しました。また、１つの郵便番号が２つの選挙区に分かれるもののリストを作成しました。
[postal2senkyoku20171004.zip](https://github.com/codeforjapan/codeforelection/files/1356429/postal2senkyoku20171004.zip)
[２選挙区に分かれる郵便番号.xlsx](https://github.com/codeforjapan/codeforelection/files/1356445/default.xlsx)
