### ISSUE TITLE
Minor Issues: 気になったことを書くスレッド

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#33]
質問事項がいろんなスレッドに乱立すると混乱するので、質問とか気になったことはこのスレッドに書きましょう。

**Comment by higa4** [comment]
@hkwi さん、GrayDBの年齢欄について、共産党候補は党のサイトで年齢のみが公開されています。生年月日は逆算で生年を計算する感じになると思いますが、GrayDB上にはどのように入力したら良いですか？「手入力年齢」欄を作る？

**Comment by higa4** [comment]
ああっ、よく探したら生年月日が出ているのもありました。
http://www.jcp-hyogo.org/blank-2
が、やはり年齢しか出していない候補者もいる。。

**Comment by higa4** [comment]
@Tetsuya SATO さんか誰か詳しい方教えてください。下記ページの中央ちょっと下付近に「菊池　憲之」さんという立候補者がいて、「新社会党」の兵庫県本部書記長でありつつ、「無所属」で出馬しています。
http://www.jcp-hyogo.org/blank-2
こういう場合、この方の所属政党はずっと「新社会党」ということで良いのでしょうか。それとも選挙期間中だけ「無所属」ということになりますか？

**Comment by hkwi** [comment]
年齢の件 ＞ そうなんですよね。日付が分からない場合は、wikidata 的な解決方法としては、1月1日をダミーデータとして入れるというやり方でどうでしょうか。

さらに行くと、本人の公式サイトに誕生日が載っていることもあります。あと facebook とかに記載されていたり。調べだすと大変すぎるので、いったんは 1/1 ダミーがいいかと。

**Comment by higa4** [comment]
1月1日に仮置きしても良いですが、wikidata側には月日を指定せずに年だけ入れるというやり方もあります。精度は年（最大１年の誤差はある）という形です。

**Comment by hkwi** [comment]
実は年だけで入れた生年月日は SPARQL で取得すると `"YYYY-01-01T00:00:00+00:00"^^xsd:dateTime` で返ってくるのを観測しています ^^ なので、誕生日で SPARQL Query するのは実は関数を使わないと上手く取れなかったりしました。

GrayDB のいくつかが 1/1 で入っているのはこのためだったのです…。

まー実用上はどっちでもいいかなぁ。
- 年齢を直接入れるときは誕生日の欄を空欄に
- 年齢を計算で出しておきたい場合は 1/1 をダミーデータに

というのでどうでしょう？

**Comment by higa4** [comment]
なるほどー。1/1にしましょう

**Comment by hkwi** [comment]
無所属にするのがいいのか、連立をそのまま表現したほうがいいのか… popolo JSON 的には…membership
 を頑張って複数回書けば表現できないこともない、か。むむむ。

**Comment by higa4** [comment]
@Tetsuya SATO(Designrule) さんかどなたか、もうひとつ教えてください。
データのwikidataへのインポートについてmySocietyのメンバーとやりとりしているのですが、玄葉光一郎 (Q58213)さん
https://www.wikidata.org/wiki/Q58213
の公職(P39)のところに、mySociety側が下記の文を追加しました。
parliamentary term(P2937:議会開催期)-47th House of Representatives(第47回衆議院)

これについて、当方より国会の会期と選挙は下記のように紐付いていないという説明をしたのですが
http://www.shugiin.go.jp/internet/itdb_annai.nsf/html/statics/shiryo/kaiki.htm
会期(parliamentary session)と議会開催期(parliamentary term)は別物で、後者は選挙と紐付いて入れ替わる(同じ「第47回」で合っている)と主張されています。
この「第47回衆議院」（「第47回衆議院選挙」ではない）という衆議院に選挙と同じ連番が付く概念は日本では存在するのでしょうか。衆議院自体に選挙と同じ連番が付いていることに素人的には違和感があるのですが。

**Comment by hkwi** [comment]
補欠選挙したりするし、
「玄葉光一郎 」-「公職」-「第47回衆議院議員」
という紐づけをして、任期を設定、
「第47回衆議院議員」-「上位？」-「衆議院議員」
「第47回衆議院議員」-「構成役職」-「第47回衆議院」
という感じ？でしょうか…データモデルの設計問題ですよね。

そうなんですよね… wikidata はこの辺のスキーマ（＝ユースケースによって変化する）が合意しにくい問題があるような気がしていて、あるある事例な感じはするのです。逆に彼らのスキーマで「これだと上手く使えなくて困る」というユースケースを提示してみるとか。「こっちのほうがいいよね？」と言ってみるとか。

**Comment by higa4** [comment]
ありがとうございます。はい。データモデルは国ごとに違うものが結構あるのですが、プロジェクトが（よくあるように）欧米に牽引されているので、その違いは丁寧に説明していくしかない感じです。ウィキデータの日本コミュニティはまだコミュニケーションが少ないので、まずは日本としてのデータモデルを分野ごとに整備していく必要があると感じています。
それはさておき、モデルとしてはhkwiさんご指摘の形がまさにmySociety側が提示しているもので、美しいのですが、日本の衆議院に第n回という概念ってあるんだろうか、というところがよくわからなかったのです。。

**Comment by hkwi** [comment]
あーなるほど。日本のシステム上（法律上）どういう枠組みかという話ですね。であればそれに沿ったスキーマ案を提示するしかないかも。私は門外漢なのでよくわかりませんｗ！

**Comment by Yfuruchin** [comment]
@higa4 さん（でいいのかな）、立候補情報が流れていたものの、立候補取りやめの場合は何かフラグを立てますか？それとも行削除？

たとえば北海道11区の佐々木とし子さんは10/5にとりやめ表明とあります
http://tkc-jcp.blogspot.jp/2017/10/blog-post.html

**Comment by higa4** [comment]
そういうの、フラグを立てたいです。列を作るので、何かあればご指摘ください。
