### ISSUE TITLE
プロジェクトの紹介ページを作成

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#4]
外部の方に本プロジェクトについて紹介するためのシンプルなサイトを作る。
github pagesを想定（かな？）。

その場合
codeforjapan/　以下にgithubpage用のレポジトリを作るのかと思います。
権限のある方お願いします。

**Comment by KuNi1138** [comment]
もともとCfJのウェブにProjectを作成する計画があったので、
http://www.code4japan.org/
に作成しましょうか？
トップに動線作って。ご意見ください。

**Comment by halsk** [comment]
CfJ のプロジェクト紹介ページは別に作るとして、このプロジェクトは単体で作るのが良いかと思います。
リポジトリ作りますね。

**Comment by halsk** [comment]
https://github.com/codeforjapan/codeforelection_front
作りました。フロントページに関する Issue はそちらでやりましょう。
こちら一旦クローズします。
