### ISSUE TITLE
postal2senkyoku.light.json に一部選挙区が含まれない

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection#40]
現在のところ、下記の選挙区が含まれていないことを確認。
* 鹿児島（43）の第3選挙区
* 埼玉（11）の第7選挙区

その他のフルバージョンのJSONについて同じ現象が発生しているか未確認

**Comment by tetsuyas1** [comment]
通常版は問題ないみたいです
公示日で別の作業を優先しますので一旦外れます
