### ISSUE TITLE
告示当日の作業を整理する

### ISSUE THREAD

**Issue by higa4** [codeforjapan/codeforelection#41]
1.立候補者確定情報をGrayDBに更新->佐藤さん
2.公開して問題の無い情報かできるだけチェックする->東(例：fbやtwitterがリンク切れしていないか、別の人にリンクしていないか等)
3.Front UI ができていたら、それを使って常識の範囲でチェックする。->松原さん、佐藤さん

漏れ、過不足などありましたら足してください。

**Comment by hkwi** [comment]
1.の「立候補者確定情報をGrayDBに更新」は「届け出順 」あるいは「比例名簿順位」が埋まったら確定したとみなす、という感じでしょうか…？ここは手分けする感じになると思うので、完了している目印があると良いかなと思います。

**Comment by higa4** [comment]
> 1.の「立候補者確定情報をGrayDBに更新」は「届け出順 」あるいは「比例名簿順位」が埋まったら確定したとみなす、という感じでしょうか…？ここは手分けする感じになると思うので、完了している目印があると良いかなと思います。

はい、そのとおりです。アナウンスしていなくてすみません。確定の判断が素人だとぶれるので、佐藤さんにタイミングを見計らってもらってご指摘の2項目を埋めてもらいます。明日何時になるかは状況次第です。

**Comment by higa4** [comment]
その後の手順について、hkwiさんの方で何かお考えのことがあれば教えてください。今のところまだ詳細には決まっていません。

**Comment by hkwi** [comment]
とりあえず popolo JSON 形式の出力（選挙版）は私のほうでたたき台やってみます。サブセットになると思います。

**Comment by nyampire** [comment]
これはいったんCloseでよいかな？

popolo JSONの出力は別途Issueをたてましょう。

**Comment by nyampire** [comment]
問題なさそうなのでclose
