### ISSUE TITLE
Facebook/Twitterアカウントの継続的メンテのための仕組みについて

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#45]
# Facebook,Twitterアカウントの自動メンテを目指す

## やり方
1. Bing Search APIで、"安倍晋三　 あべしんぞう Facebook" , "安倍晋三　 あべしんぞう Twitter" といったクエリで検索する。
  - 今のところ有料っぽい（数千円 ）
2. 存在すれば、FacebookPageか、Twitterのアカウントページが取れるので、そのページを記録
3. 発言内容の取得
  - Facebook Graph APIから、当該Pageの発言内容を取得する
  - TwitterAPIから、当該Tweetの発言内容を取得する
4. 当該内容を政治家の発言っぽいかどうか判定する分類器で判定する
5. 政治家だと判定したら当該政治家のアカウントとして認定する。
6. その上で余裕があったら、人手で確認する。

## 政治家の発言を判定する分類機の作成（Facebookの場合・Twitterもほぼ同様）
- 100人程度の政治家のFacebookPageの発言を取得する
- それ以外のFacebookPageの発言を取得する（政治家っぽくないって、どうすればいいのかな？）
- 単語ベクトル化して、分類器を構築する

## その他
- 地方政治家などへも拡張すると良さそう
- 政治家以外にも使えるのではなかろうか。。。

**Comment by hkwi** [comment]
作業中発見した新たな事実として「twitterアカウント移行していることがある」というのがあります。
- wikidata 的に開始日と終了日を設定できる
- twitter アカウントは開始日を表示していたはず
- 終了日は watch していないとわからないはず

ということで、daily で死活監視する bot を作るのも良さそうです。

**Comment by tetsuyas1** [comment]
トライアルしてみた結果、Facebookはかなりの確度でデータ取れそうな感じです。Twitterはクローリングが微妙なのかもしれません。ひょっとすると、TwitterのAPI叩くっていう方法もあるのかもしれない

**Comment by tetsuyas1** [comment]
こちら一応結果をマージしましたのでご報告します。別イシューに移行します
