### ISSUE TITLE
GrayDB: 登録済みのWikidataで削除されてしまったものがある

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection#46]
昨日登録したGrayDBの候補者データのうち、削除されてしまったものがあるようです。
どうも最初の10件程度が怪しいようです（Q41733953 〜 Q41743870）。

**Comment by hkwi** [comment]
ソートされて位置が移動したというではないでしょうか…？

今のところ git log 上は消えたことはないようです。

**Comment by takahashim** [comment]
たとえば https://www.wikidata.org/wiki/Q41734733 (GrayDbId 427)がそのうちの一つで、

> このページは削除されています。 参考のため、このページの削除、保護、移動の記録を以下に表示します。
>
> 2017年10月9日 (月) 06:15 MisterSynergy (トーク | 投稿記録) がページ「Q41734733」を削除しました (Empty item: content was: "", and the only contributor was "221daisuke" (talk))

と表示されてました…。

**Comment by hkwi** [comment]
あぁ、wikidata 上で削除されているということですね。これは…メタデータをちゃんと入れてないからゴミとみなされたんだろうなぁ…。

**Comment by takahashim** [comment]
たぶんそうなんでしょうねえ… ＞ メタデータをちゃんと入れてないからゴミとみなされたんだろうなぁ…。

削除されてるのは以下の10件のようです。

```
Q41733953
Q41734733
Q41735254
Q41736673
Q41737672
Q41737955
Q41738948
Q41742328
Q41743319
Q41743870
```

とりあえずこの10件は作り直して、それ以外についても決め打ちメタデータは登録しておきます。

**Comment by takahashim** [comment]
削除されてなかったQ417...で始まる候補者について、P31（分類）がQ5（ヒト）、P106（職業）がQ82955（政治家）、というデータを登録しました。

**Comment by takahashim** [comment]
上の10件に対して再登録をしてWikidataIDを再発行しました。新しい番号は以下の10件になります。

```
Q41794089
Q41794090
Q41794091
Q41794092
Q41794094
Q41794095
Q41794096
Q41794097
Q41794100
Q41794101
```

GrayDBには新Wikidata IDを反映済みです。また、この10件についても、P31（分類）がQ5（ヒト）、P106（職業）がQ82955（政治家）、というデータを登録しました。これでゴミ扱いされないとありがたい…。

**Comment by takahashim** [comment]
対応したのでこのissueは閉じておきます。
