### ISSUE TITLE
報道データとの確認作業

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#47]
- GrayDBのAZ列以降に作業の結果を掲載

## 作業内容
- "ひらがなのよみがな"(性と名の間に半角スペースを含む）をキーとしてマッチング
- BB列には、小選挙区の立候補情報を掲載
- BC列は小選挙区候補の重複
- BD列は比例（のみ）立候補の情報
- BEはこれらの整理状況
- すべてソート済み

## 3_該当なし　について
GrayDBには存在したが、報道データでは確認できなかったものが該当

### GrayDataになく、報道データで新たに把握した部分
- 立候補者シートのQ列に"把握漏れ"とある行は、GrayDbにひらがなふりがなの登録が見つからなかったデータである。
- 作業上の都合で、把握漏れのみを抽出したシート　立候補者(把握漏れ　を作成した
- 300件ほど存在。
(ふりがなのマッチングがとれずに、上記3_該当なしに含まれている恐れもあるので要確認)

## ふりがなについて
- wikipediaの表記と政党公式で濁音などはことなるケースも有り、
- キーとして若干弱い。また、同姓同名も存在しているので要注意
- ふりがなの姓名との間を半角スペースで分割するポリシーは改善したほうが良いかも。
  - 作業が少しやりにくい
  - 全角スペースが入っているケースが有る
  - （ただし、GSSでは全半角を区別していない模様ではある。）

**Comment by higa4** [comment]
作業お疲れ様です。確定した立候補者はH列（立候補）に「確定」もしくは「立候補」と入れると良いかなと思いますが、
・842行目までが小選挙区立候補者（重複立候補含む）
・955行目までが比例区立候補者
・以下は立候補が確認できなかった人
という理解で合っていますでしょうか。

**Comment by tetsuyas1** [comment]
@higa4 その理解であってます。"確定" の文字列入力しました。

**Comment by higa4** [comment]
ありがとうございます！
報道では立候補者数は1170と言われていますが、数えてみると現在960人なので、あと210人ほど漏れていますか？

**Comment by tetsuyas1** [comment]
立候補者(把握漏れシートの中に　報道されたが既存Grayに入ってない　人のリストがあります

**Comment by higa4** [comment]
了解です！wikidataへの一括追加用にこのリストは残しつつ、メインの立候補者リストの方にもマージすると良いのかな。合計数が1170より多くなる？

**Comment by hkwi** [comment]
ふむふむ。完全無所属はすっぽり抜けてるのね。なるほど。

**Comment by tetsuyas1** [comment]
そういうことでいいと思います。
なお、ソーシャルアカウントの取得が大量なので #45  を試してみようと思っています。
実用に堪えるかどうかはちょっとお時間ください

**Comment by hkwi** [comment]
あ、「立候補者(把握漏れ」シートで作業中なのですね。では私のほうでは、とりあえず追加作業は控えておきます（いくつか入れてしまいましたが…）。

**Comment by tetsuyas1** [comment]
シート上では作業していただいて問題ないです。 @hkwi  手元で当該人名でBing検索を試しているレベルですので。

**Comment by higa4** [comment]
最終的な候補者一覧の整備に際して合計数が把握できるように、現在GrayDBの953行-1052行にある立候補を取り下げた人たちをいったん別シートに逃したいのですが、よろしいですか？ 
→これ、特にコメントが無かったのでこれから手動でやりますね。何かあれば戻せますので言ってください。

**Comment by higa4** [comment]
逃しました。これで候補者988人になりました。

**Comment by hkwi** [comment]
把握漏れをほぼカバーするであろう候補一覧を機械処理で抜き出してみました。

https://github.com/hkwi/shuin48pre/blob/master/docs/gray_to_asahi_missing.csv
https://github.com/hkwi/shuin48pre/blob/master/docs/gray_to_mainichi_missing.csv

意外と旧字体とかで重複したりするので、投入するときは、もうひと手間かけないと駄目かもですが、これらは自動ビルドで追跡しています。

朝日との差分のほうが情報を上手く抜き出せてるので、より適切かも。

**Comment by nyampire** [comment]
GrayDB側で立候補者リストが完成したのでこちらClose
