### ISSUE TITLE
ワイヤー作る

### ISSUE THREAD

**Issue by ts020** [codeforjapan/codeforelection#5]
figmaにログインして直接編集してもらえればみんなで編集できます。
https://www.figma.com/file/BGj2XtpDLNi4KW9drK6HJ53V/code-for-%E9%81%B8%E6%8C%99-%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3

日本語入力するのに下記から、fontインストーラーを入れるか、デスクトップアプリを入れる必要があります。
https://www.figma.com/downloads

**Comment by nyampire** [comment]
フロントエンドのデザインはほぼ決まったので、Close
