### ISSUE TITLE
GrayDB: 比例区の表記ゆれ

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection#50]
GrayDBの候補者シートで、比例区(P列)の表記ゆれがすごいです…。
sortしてuniq -cした結果は以下のようになります。
（右が表記で左が件数です。一番上の814件は空欄のものです。）

```
 814 
   8 中国
   6 九州
   7 四国
  10 東京
  11 東北
  15 東海
  21 近畿
   4 北信越
   8 北海道
  13 北関東
  12 南関東
   2 東京都
   1 比例区
   6 北陸信越
   2 九州・沖縄
   1 東北ブロック
  16 北信越ブロック
   5 北海道ブロック
   2 東京都ブロック
   7 比例中国ブロック
  20 比例九州ブロック
   4 比例四国ブロック
  11 比例東京ブロック
   8 比例東北ブロック
  16 比例東海ブロック
  19 比例近畿ブロック
   4 比例北海道ブロック
  12 比例北関東ブロック
  13 比例南関東ブロック
  12 比例北陸信越ブロック
```

あまり長くする必要はないと思うので、「比例」と「ブロック」を削って、以下で統一するのでどうでしょうか。

```
北海道
東北
北関東
南関東
東京
北陸信越
東海
近畿
中国
四国
九州
```

**Comment by tetsuyas1** [comment]
賛成です。

**Comment by higa4** [comment]
「比例」と「ブロック」が付いた名前はwikidataの項目名なんです :) まぁ、投入時に変換すれば良いことなので短く統一して頂いても構いません。

**Comment by tetsuyas1** [comment]
個人的は、番号の列があり、そちらから変換すればよいかと思っていました

**Comment by higa4** [comment]
はい。それでよろしいかと思います。

**Comment by takahashim** [comment]
@tetsuyas1 @higa4 これなんですが、実は比例ブロックのコードの列が現在ないんですよ…。
O列とP列の間にでもカラム追加しちゃっても大丈夫ですかね？

**Comment by higa4** [comment]
Front側が見ているカラムのズレが問題無いのであれば大丈夫だと思います。

**Comment by hkwi** [comment]
カラムの参照が文字列経由に変わっていたはずなので、大丈夫のはず。いっちゃってください。

**Comment by takahashim** [comment]
ちょっとcodeforelection_frontのissueで聞いてみますね

**Comment by takahashim** [comment]
比例ブロックのコードはなくてまあよいか、ということになりました。
表記自体は短いもので統一しました。

```
$ sort hireiku.txt |uniq -c|sort -n
  34 四国
  42 北海道
  55 中国
  56 北陸信越
  67 東北
  84 東海
  88 九州
  93 北関東
 104 東京
 105 南関東
 127 近畿
 325 
```

**Comment by rish314** [comment]
フロント側のマスタを整備し直す必要が有りますね。
こちらで作業しておきます。
