### ISSUE TITLE
継続的メンテの自動化検討

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#51]
related #45 
- 今後の継続的メンテナンスについて検討するイシューです。

**Comment by tetsuyas1** [comment]
@higa4 さん(これIDコールになるのかな？）wikipediaのURLの機械的登録を考えたいと思います。こちらでご相談できればと思います。

**Comment by higa4** [comment]
ありがとうございます。ちょうど私の方でもwikidataの整備をこれからどうするかまとめているところだったのでこちらで共有させてください。

**Comment by higa4** [comment]
しばらく止めていたwikidataへのデータ登録を再開するために、GrayDBにあるものをできるだけ活かしつつ、二重登録や不整合を極力抑えるために作戦を立てたいと思います。案を考えてみましたのでご意見お願いします。

1 GrayDBから転記するもの

1.1 wikidataにほぼ未登録で、問題が少なさそうなもの
→そのままQS2などで一括登録
・選挙区
・公認政党
・47th House of Representativesなど（命名をどうするか検討中）

1.2 wikidataにある程度登録済みでかつGrayDBの文字列をそのまま登録するもの
→GrayDBの登録内容のうち、wikidataに入っていない差分を取ってから未登録分を一括登録
・選挙用表記名
・かな
・誕生日
・写真
・twitter
・facebook
・LINE
・youtube channel
・instagram
・公式サイト
・メールアドレス
・公式ブログ
・詳細情報URL

1.3 wikidataにある程度登録済みでかつGrayDBの文字列をQ番号に置き換えて登録するもの（置き換え数の少ないもの）
→GrayDBの登録内容のうち、wikidataに入っていない差分を取ってから未登録分を一括登録
・性別

1.4 wikidataにある程度登録済みでかつGrayDBの文字列をQ番号に置き換えて登録するもの（置き換え数の多いもの）
→手作業で登録
・出生地
・立候補歴
・当選歴
・学歴
・職歴
・公職
・父親
・配偶者

2 GrayDB以外のネット上から収集して手作業で登録
→広く作業支援を呼びかける

3 データのupdate
・botを仕込む？

4 当選後に向けた準備
・何をしましょうかね？

**Comment by higa4** [comment]
あ、こちらはGrayDBのメンテ用スレッドですかね？

**Comment by tetsuyas1** [comment]
こちらは本来自動化の検討のためにあるので、
https://github.com/codeforjapan/codeforelection/issues/61
　こちらのスレッドに移動しました。

**Comment by nyampire** [comment]
議論が移動したようなのでクローズします
