### ISSUE TITLE
GrayDB: 立候補者数を1180に合わせる

### ISSUE THREAD

**Issue by higa4** [codeforjapan/codeforelection#52]
2017/10/12現在のGrayDB立候補者件数：1184
-Q41770921「近藤秀子」：取り下げのため削除予定

**Comment by higa4** [comment]
-(Q番号未登録)広次忠彦：取り下げのため削除予定
https://www.jiji.com/jc/article?k=2017090600859&g=pol

**Comment by higa4** [comment]
(Q番号未登録)山口陽規：取り下げ(息子が出馬)のため削除予定

**Comment by hkwi** [comment]
山口陽規 さん
広次忠彦 さん
松本隆 さん

**Comment by higa4** [comment]
ああ、松本隆 さん削除でピッタリ1180ですね。

**Comment by higa4** [comment]
(Q番号未登録)松本隆：取り下げのため削除予定
