### ISSUE TITLE
振り返りの日時・ロジ決定

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#53]
# 目的
- 今回のデータ作成についての振り返り、改善点などを話し合うミーティングを持つ

# スケジュール
- 選挙終了後？かな？

# 議題
- 今後政治家データを収集、蓄積していく際にどのような方法論がそもそも望ましいか
- 政治家のユニークなIDをどのように定義できるか
  - wikidataとの連携を視野に
- 機械化・半自動化できる部分とのその有効性について
  - CIによる処理についてやり方の共有
  - Travis,circleCIの長所短所？
- 人力メンテナンスの効果的なやり方
- 必要に応じてExcel（GoogleSpreadSheet）教室

# メンバー
- 希望者・今後継続的に集めていきたい人

**Comment by nyampire** [comment]
[Slackで議論中](https://cfj.slack.com/archives/C7A52QE80/p1508753417000127)ですー。
