### ISSUE TITLE
mySocietyへの提供データ作成

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection#58]
フォーマットに沿ったシートをGrayDbのforMSシートに作成した。
このシートはGrayDB候補者シート、選挙区マスタ、政党マスタを合成して作られている。
直接修正せず、それぞれの元データを修正するようにしてください。

- [x] 諸派、無所属について、政党マスター対応がなさそう
- [x] wikipediaURLには何を入れるのか？？
- [x] area_name_idはあれでよいか？

**Comment by takahashim** [comment]
無所属のWikidata IDはQ327591だそうです https://www.wikidata.org/wiki/Q327591
spreadsheetの政党マスタに入れておきました

**Comment by takahashim** [comment]
「諸派」というラベルのついた項目はないですが、ミニ政党 (Q354239)の別名が「諸派」のようです
https://www.wikidata.org/wiki/Q354239
こちらも政党マスタに入れておきます
