### ISSUE TITLE
Wikidata:Notability

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection#62]
> About all the items about politician, if you don't add reference I will delete all that don't fall under Wikidata:Notability. Can you add the source on this item?

と言われたのですが、どういうふうにreferenceを追加すればいいんでしょうか？

**Comment by hkwi** [comment]
出典あるいは出典URLでしょうね。https://hackmd.io/BzDGE4FMAYGYDMC0AjYBWNiAs9m0ePKJCgExQDsAjACZXizgVA==#12-%E9%85%8D%E6%85%AE%E4%BA%8B%E9%A0%85 
ちなみに元の言われたのは wikidata の議論ページでしょうか？

**Comment by takahashim** [comment]
https://www.wikidata.org/wiki/User_talk:Takahashimm#Politician 指摘はここで受けました。
選挙公報のURLあたりが良いのでしょうか。

**Comment by higa4** [comment]
ああ、ちゃんとしておけばよかったですね。はい。出典URLとしてkouhosha.infoをかけば良いと思います。

**Comment by higa4** [comment]
閲覧日 (P813)もペアで、入れた日付を入れればよいと思います。

**Comment by hkwi** [comment]
信頼性の高い出典であればあるほど良いはずですが、まだ選挙公報の URL 集め終わってないんですよね…暫定的には asahi.com でしょうか。出典用の RDF 生成しますね。

**Comment by hkwi** [comment]
あぁ、kouhosha.info 出典にしますか。それでもいいですね。

**Comment by takahashim** [comment]
とりあえず立候補選挙（P3602）→第48回衆議院議員総選挙（Q20983100）の出典URLを"kouhosha.info"にしてみます。

**Comment by takahashim** [comment]
とりあえず対応したつもりなので閉じておきます。
