### ISSUE TITLE
popolo JSONを作成する

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#63]
候補者の一覧がFixしたので、popolo JSONを作成する。

作成したら、フロントエンドのTOPページからダウンロードできるようにする？

**Comment by hkwi** [comment]
#55 でとりあえず作ってはあります。データの格納方法については議論があるかも。

**Comment by nyampire** [comment]
作成方法がある程度わかっているのでクローズ。
格の方法については別途協議。
