### ISSUE TITLE
参議院と都道府県知事のデータを集める

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#64]
mySocietyに渡すためのリストを作成する。

[参議院](https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit#gid=147070354)については https://github.com/codeforjapan/codeforelection/issues/60#issuecomment-336619089 で作成された一覧をもとにリストを作る。

- [x] Wikidata上でデータ登録して wikidata id を取得する
- [x] 出馬している選挙区の調査
- [x] Facebook Page (あるいは個人ID) の調査

[都道府県知事](https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit#gid=1494486345) についても同様。

- [x] Wikidata上から一覧データを取得する
- [x] Wikidata上にIDが存在しない知事をデータ登録して wikidata id を取得する
- [x] 出馬している選挙区の調査 → 知事選挙ではこの概念が存在しないような？ たぶんなくてもよいので、mySocietyに要確認
- [x] Facebook Page (あるいは個人ID) の調査

**Comment by nyampire** [comment]
mySociety（Matt）から、「参議院の議員のスクレイピングをしたいのだけど、どこがオススメ？」と聞かれています。

[参議院の議員リスト](http://www.sangiin.go.jp/japanese/joho1/kousei/giin/194/giin.htm)と、その[英語版](http://www.sangiin.go.jp/japanese/joho1/kousei/eng/members/index.htm)を回答する予定。

メモ：参議院の議員の顔写真については、[参議院に対して利用許諾を得る](http://www.sangiin.go.jp/japanese/chosakuken/index.html)必要がありそう。

> ホームページに掲載している写真等の画像については、無断で転載・複製することはできません。写真等の画像を使用したい場合は、webmaster@sangiin.go.jpへお問い合わせください

**Comment by nyampire** [comment]
知事の一覧については https://github.com/codeforjapan/codeforelection/issues/60#issuecomment-336702414 にて抽出済み。

**Comment by nyampire** [comment]
GrayDB上にシートを作成しました。

* [参議院議員一覧](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=246404692)
* [都道府県知事一覧](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=1148969338)

**Comment by nyampire** [comment]
参議院、いきなり「アントニオ 猪木 [猪木 寛至]」と通称表記で頭をかかえているｗ

**Comment by takahashim** [comment]
都道府県知事の方は http://tinyurl.com/yazwajuo の方がたくさん情報がとれるのでどうぞ

**Comment by higa4** [comment]
SPARQL使いこなしてますねーすごい！

**Comment by takahashim** [comment]
参議院の方も試してみました http://tinyurl.com/ya6ce6q5 が、終了日（P582）の情報が入ってないので過去の参議院議員も出てきて役に立たなさそうですね…。

**Comment by hkwi** [comment]
参議院は解散総選挙みたいな仕組みではないので、Term で絞り込むこともできず、むむむ、どういう方法がいいんだろう。

**Comment by nyampire** [comment]
おー、ありがとうございます！

wikidataからは、ひとまずあるだけ抜ければそれでよいと思っていて、このCSVをもとにVLOOKUPで引っ張れば、いまあるデータとしては十分なんじゃないかと思います。氏名の重複には気をつけないといけないですが、とりあえずwikidata idが欲しい。

**Comment by nyampire** [comment]
mySocietyからの質問「参議院のデータ、スクレイピングするのにどのサイトがいいのかな」って、もしかして、過去の新聞社の選挙サイトみたいなものをイメージしてるのかな。。。（例：[こういうの](https://www.nhk.or.jp/senkyo/archives/sangiin/2016/)）

ちょっと権利的にグレーな気がしているから、あまりオススメはできない気がするのだけど、参議院議員であればほとんど増減ないだろうし、元データにしたいのはわかる。

**Comment by hkwi** [comment]
とりあえずできる範囲で Q name 埋めてみた。

**Comment by takahashim** [comment]
参議院のリスト、見た限り「別名」フィールドが欲しいですね…。特に女性で旧姓を使われている方が散見されます。
それとも「名前（フル）」を「名前（姓）」＋「名前（名）」じゃないものにしてしまってもいいんでしょうか。「橋本聖子」「石崎」「聖子」のような形です。

**Comment by takahashim** [comment]
ちょっと参議院のデータを見てみましたが、礒崎哲史氏はWikipediaでは「【磯】崎哲史」になってますね…。これはWikipediaを修正するべきなんでしょうか。
https://ja.wikipedia.org/wiki/%E7%A3%AF%E5%B4%8E%E5%93%B2%E5%8F%B2
ちなみに「礒崎陽輔」氏はそのまま登録されています。
https://ja.wikipedia.org/wiki/%E7%A4%92%E5%B4%8E%E9%99%BD%E8%BC%94

**Comment by takahashim** [comment]
公明の竹内真二氏以外のqidを埋めました。竹内氏だけWikipediaに登録されてなさそう…。

**Comment by nyampire** [comment]
GrayDB上に別名フィールドをつくりました。mySocietyのシートにも、alt_nameとしてカラムを作成しました。

**Comment by nyampire** [comment]
Wikipedia側がまちがっていそうなエントリ "礒崎哲史 / 磯崎哲史" については、どういう対応がよいのか、Wikipediaのひとに聞いてみます。

https://github.com/codeforjapan/codeforelection/issues/64#issuecomment-337113564

**Comment by nyampire** [comment]
Wikipediaのページ「[礒﨑哲史](https://ja.wikipedia.org/wiki/%E7%A4%92%EF%A8%91%E5%93%B2%E5%8F%B2)」に関しては、リダイレクトなど、必要そうな作業をやってくれるそうです。
今日明日くらいには完了する予定、とのことです。（ありがたい）

**Comment by nyampire** [comment]
知事のデータを確認中。茨城県の知事が、今夏で交代していたのでメモ。

新しいIDは [Q38081041](https://www.wikidata.org/wiki/Q38081041)

**Comment by nyampire** [comment]
知事に関してはひとまず完了しました。

**Comment by nyampire** [comment]
Wikipediaのページ「[礒﨑哲史](https://ja.wikipedia.org/wiki/%E7%A4%92%E5%B4%8E%E5%93%B2%E5%8F%B2)」に関して、知人のWikipedianが以下の修正をしてくれました。
リダイレクトで正しいURLに到達できるようになっています。

1. 記事名を「礒崎哲史」としました。
2. 「礒崎哲史」本文右側に本来は「﨑」だというタグ表示を加えました。
3. 本文中の﨑はそのままです。
4. 「礒﨑哲史」「磯崎哲史」でも「礒崎哲史」に転送されます。

5. ウィキペディアを全文検索して、磯崎を礒﨑に変更し礒崎に飛ぶようにしました。漏れがなければウィキペディア日本語版の記事内には磯崎哲史の文字列はなくなったはずです。

**Comment by nyampire** [comment]
参議院のデータを作成中です。

https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=246404692

2点、氏名に関して、ちょっと気になるところがあります。

* 「アントニオ猪木」のパースにとても違和感がある。性と名を分ける必要がないかも？
フルネーム：アントニオ猪木
名：猪木
姓：アントニオ
別名：猪木寛至

* 「蓮舫」の姓名で、姓がnullになるけど大丈夫？
フルネーム：蓮舫
名：蓮舫
姓： -null-

**Comment by hkwi** [comment]
シート上では、「名前（フル）」のコメントには「本名」と書いてあるので、「猪木寛至」が正になりそう。
「アントニオ猪木」は分割不能な 1 word で、「姓＋名」では**ない**ので、これ単体で名前として登録するしかないと思います。それは「蓮舫」も同様で。
ただし wikidata 上でのラベル名が「本名」であるべきか、一般的に認識されている「名称」であるかは、ちょっとわかりません。通称のほうがラベル名であるべき気はします。

**Comment by nyampire** [comment]
ありがとうございます。
いちおう、本名のほうにシートを直しておきました。
でもそうすると、他の、旧姓で政治活動してるかたも本名にするべきなのかもしれないと思っていて、wikidataの情報を更新するときなどに、別名に値があるひとは注意が必要かも。

**Comment by nyampire** [comment]
参議院、ひとまず100まで終わりました。あと150くらい。時間はかかりますが、候補者よりも圧倒的にサイトが整備されているので、流れ作業です。

ここまでのところ、どうしようかポイントは以下です。

* "竹内真二"さんのWikidata登録
* 参議院の選挙区は、都道府県単位＋比例代表だと思うのですが、選挙区はwikidataのP768(Q1052894)で大丈夫？（衆議院と変えなくてよい？）

**Comment by hkwi** [comment]
根拠となる法律が違ったような…参議院合同選挙区とかは、個別にエントリを作るべきな気がする…

**Comment by nyampire** [comment]
> "竹内真二"さんのWikidata登録
こちら [Q42323636](https://www.wikidata.org/wiki/Q42323636)で登録しました。

参議院の選挙区の記載方法は、僕からmySocietyに確認します。

たぶん、都道府県番号を列挙するレベルでよいと思う。いちおう、参議院の選挙区はwikidataにIDがあるみたいなので、調べようと思えば調べて入力可能な状態。

**Comment by nyampire** [comment]
[参議院議員](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=246404692)のSNS、公式ページ、生年月日の調査完了です

**Comment by nyampire** [comment]
参議院議員のシートを埋めました。

参議院のページと本人のウェブページでは、[平山佐知子の所属政党が民進党](http://www.sangiin.go.jp/japanese/joho1/kousei/giin/profile/7016033.htm)と書いてあるのですが、[wikipediaでは無所属](https://ja.wikipedia.org/wiki/%E5%B9%B3%E5%B1%B1%E4%BD%90%E7%9F%A5%E5%AD%90)になっていて、[民進党のページ](https://www.minshin.or.jp/member/6181)でも404になっていたので、離党したのかも。

このへん、マスターがどこになるのか、経緯なども含めて非常にわかりづらいですね。。。

**Comment by nyampire** [comment]
集めたのでクローズ
