### ISSUE TITLE
GrayDBの不要シートの削除

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#65]
[GrayDB](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=0)に作業用のシートが大量に作成されているので、一段落したら整理が必要（22日以降かな）

**Comment by takahashim** [comment]
「候補者WikidataID取得用」は不要になったというか、`WIKIDATAQID()`関数が期待したようには動作しなかったので削除しておきます。
「候補者(Q番号未登録分_20171012_0813時点)」も削除してしまってよいかと思います。

**Comment by takahashim** [comment]
「候補者(Q番号未登録分_20171012_0813時点)」も削除しました。

**Comment by nyampire** [comment]
だいたい消したのでクローズ
