### ISSUE TITLE
選挙区に対して、area_id (区コード) の割り振りは可能？

### ISSUE THREAD

**Issue by nyampire** [codeforjapan/codeforelection#67]
mySocietyからのリクエストで、選挙区に対して area_id (kucode) を割り振ることは可能か？ということを聞かれています。

https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit#gid=514555971

いまのところ、以下で回答してるのですが、もしよりよいアイデアあったらいただけるとうれしいです。

* 公式に、エリアに対してIDは割り振られていない
* もしコードが欲しい場合、プロジェクトの内部限定コードとして、作成・付番することはできる。例えば"北海道2区"の場合、北海道が1で2区なので、1-2、のように。（[選挙区マスタ](https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=943603147)のK列みたいなものを想定） こういうのでいいのか？

他、選挙区のバウンダリのwikidata ID (area_wikidata_id) を割り振る、みたいなものもアリだとは思います。

どういう形だと幸せになれそうでしょう？

**Comment by takahashim** [comment]
比例区があるので、コードを振るなら小選挙区か比例区かのprefixをつけていただければ。

あと、区割りが変更になったときには、変更前・変更後で同じコードを再利用しても問題ないかどうか確認した方がよさそうです。

**Comment by hkwi** [comment]
コードを新規に振るなら改正年をコードに入れたほうが良いかと思います。

**Comment by hkwi** [comment]
ざっくりとしたコードであれば、wikidata の Q name が既に全て揃っているので、それを使えばよいかと。

**Comment by hkwi** [comment]
やり取りしていてやっと意味が分かったのですが、http://www.csis.u-tokyo.ac.jp/~nishizawa/senkyoku/ の shp ファイル（ポリゴンデータ）のコードに `kucode` というのがあって、（これは見る人が見れば「都道府県コード」に二桁パディングした選挙区番号をくっつけたものなのですが）その値に対応するものが欲しかったらしい。

比例区のブロックの計算方法も聞かれると思うけど、ブロックってどこからどこまでの和をとればいいんだろう…？

**Comment by hkwi** [comment]
https://ja.wikipedia.org/wiki/%E8%A1%86%E8%AD%B0%E9%99%A2%E6%AF%94%E4%BE%8B%E4%BB%A3%E8%A1%A8%E5%88%B6%E9%81%B8%E6%8C%99%E5%8C%BA%E4%B8%80%E8%A6%A7 のブロックに従って、小選挙区結合できるように、別シートを用意したので、きっとなんとかできるだろう。

https://docs.google.com/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit

**Comment by nyampire** [comment]
Slackも含めて、対応ありがとうございます！
比例区については、QIDが入っているので大丈夫かな、と思うのですが、もし追加でなんか来たらreopenしましょうー。
