### ISSUE TITLE
Wikidata: 選挙立候補者について

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection#69]
Wikidataの方で以下のフィードバックをいただきました。どうするのがいいでしょうか。

> 申し訳ないんですけれども、基本的に選挙に立候補しただけではただの立候補者であって、当選しなければ政治家ではありません。前職で市町村議員などをやってない人物の職業として政治家を追加するのはちょっとおかしいので止めてもらえませんか。あとあまりにも情報が少ない場合は上でも管理者の方のコメントにある通り著名性がないということで削除されてしまいますので、生年月日や出身校、前職などの情報を出典つきで出した方がいいと思います。Quickstatementsなどを使うのでも作業に時間がかかってしまうかもしれませんが、よろしくお願いします。Fegerr (トーク) 07:50, 18 October 2017 (UTC)
> ( https://www.wikidata.org/wiki/User_talk:Takahashimm )

**Comment by takahashim** [comment]
とりあえず今回新規に追加した方の職業は「立候補者（Q618536）」にしておくのがよいでしょうか

**Comment by higa4** [comment]
頂いた指摘の通りだと思います。ちょっと時間は掛かりそうですがそうしますと返事して頂いてよいかと思います。私が当初政治家での一括登録をお願いしたのですみません。hkwiさんからも指摘いただいたように「候補者」が正しいと思います。なので、できるだけ情報を追加するのと、可能な範囲でまだ議員実績のない人は「政治家」を消して「候補者」にする、という感じですかね。

**Comment by higa4** [comment]
QS2はスタックしている感じなのでヘルプを仰ぎました
https://www.wikidata.org/wiki/Help_talk:QuickStatements#Cancel_batch

**Comment by higa4** [comment]
QS2開発者のMagnusが気付いて進めてくれたようです。先ほどbatchが動くようになりました。

**Comment by takahashim** [comment]
とりあえず、今回新規に追加した方について、職業の「政治家」を削除しました。

**Comment by nyampire** [comment]
こちら、完了しています？ もしそうであればクローズします。

**Comment by takahashim** [comment]
確認しました、こちら対応済みです。
