### ISSUE TITLE
当落情報の記載について

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection#71]
開票後、当選・落選の情報はGrayDBに記載することになるかと思いますが、単純に当落のみでよいでしょうか。それとも、小選挙区で当選したとか、小選挙区では落選したけど比例で復活した、といった情報もわかるようにするべきなんでしょうか。

Wikidataの方は、現状は1つのqualifier（P768:選挙区）に小選挙区と比例の両方の情報がくっついているので（公職―衆議院議員のstatementも同様にqualifierを使っているようです）、どっちで当選したのかは記述しづらそうに見えました。

**Comment by higa4** [comment]
まず、GrayDBをそのまま使うか、当選者用に分けるかについてですが、候補者属性の誤りは今後とも発見される可能性があるので、複雑にならない限り当選情報も同じGrayDBに入れたほうが整合性はとりやすいと思います。
「当落情報」については選挙区当選なのか、比例区復活なのかはファクトとして区別して表現されていることが多いのでGrayDB上はそれぞれの列の後に枠を1つずつ作って区別できるようにした方が良いと思います。
「得票数」については候補者に対するものとして、選挙区の後に1つ列を作ると良いと思います。比例区については政党単位なので、政党マスタかどこか、政党単位のくくりで記載することになると思います。

**Comment by higa4** [comment]
wikidata上の表現方法は当落をズバリ表すプロパティが無いため悩ましいですが「公職」プロパティの「衆議院議員」値に付随する修飾子として選出された方の「選挙区」を入れていくことになると思います。例：稲津久
https://www.wikidata.org/wiki/Q1159

**Comment by higa4** [comment]
@hkwi 衆議院のn期を表す表現方法について、日本語名称としては下記の表にある「実施内閣」の名称を使うのはどうでしょうか。
https://ja.wikipedia.org/wiki/%E8%A1%86%E8%AD%B0%E9%99%A2%E8%AD%B0%E5%93%A1%E7%B7%8F%E9%81%B8%E6%8C%99#.E8.A1.86.E8.AD.B0.E9.99.A2.E8.AD.B0.E5.93.A1.E7.B7.8F.E9.81.B8.E6.8C.99.E3.81.AE.E4.B8.80.E8.A6.A7
英語名称はmySociety側が挙げたもののままでも良いかも。

**Comment by hkwi** [comment]
@higa4 さん、実施内閣は「（解散総選挙を）実施（した）内閣」なので、トリガー側ですよね。Term はメンバー選出後の選挙後の期間を示すので内閣の名称が被っている期間はたぶん短いんじゃないかと…。つまりあまり適切なマッピングにならないと思いました。Sato さんの意見を伺いたいところ。
英語名称は…個人的な意見としては、日本語に翻訳しようとする人が妙な造語を作らないようなものになっていれば何でもよいかと思いました。

**Comment by higa4** [comment]
なるほど、いっこズレるということですね。日本語名は内閣が組閣された後にその名前をつけるのはいかがでしょうか。大臣の顔ぶれとかが紐づくので概念的には分かりやすい気がします。

**Comment by takahashim** [comment]
@higa4 なるほど、小選挙区・比例区両方で立候補していても、比例区で復活した場合は小選挙区の方はWikidataには書かない、ということなんですね。

**Comment by higa4** [comment]
GrayDBの下記列（選挙結果）をどなたかお時間とれる方、埋めて頂けると助かります。
Q列「当選」：比例区の当選者に「1」をセット
S列「当選」：小選挙区の当選者に「1」をセット
T列「得票数」：小選挙区の当選者の得票数をセット
https://docs.google.com/spreadsheets/d/182l2CexnCqZ0GPSg9sp2XMMfvUC4muuvYFdJp2Q-vkI/edit#gid=0

**Comment by takahashim** [comment]
S列の小選挙区については定数289人分全部「1」がついているようです。

**Comment by nyampire** [comment]
比例区についても1 を入れました。得票数の入力は未着手です。

**Comment by takahashim** [comment]
当落情報については記載済みなので、このissueは閉じてしまいますね
