### ISSUE TITLE
Popolo と Wikidata の対応調査

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection#9]
古崎さんsays:

PersonやOrganizationを見た感じでは，対応するプロパティはありそうですが，細かいチェックは後ほど
データ入力は，Wikidataには手入力になる（一括インポートは不可．ぼっとは申請したら作れるそうですが．．．）なので，
１．候補者一覧のデータをSPARQLでWikidataと照合してIDや現状のデータを取得
２．足りないデータをWikidataで手分けして入力
３．SPARQLでPolopoの形式に変換
という感じがいいかな．．．と思います．

**Comment by koujikozaki** [comment]
まずは[Polopo](http://www.popoloproject.com/)の，
- Person
- Organization
- Membership
- Post
について，Wikidataとの対応を調べる．

ざっと見た感じ，contact detailのように，Wikidataに掲載するにはそぐわないと思われるデータもあるので，そういうものは「マッピングの対象外（＝Wikidataには載せない）」方向で考える．

**Comment by hkwi** [comment]
popolo から wikidata id を参照する、というのはそれはそれで[あるんですよね](http://docs.everypolitician.org/data_summary.html)（"IDs to other data sets, including Wikidata"）。

他のプロジェクトで wikidata 監視ボットがありそうだし、マッピングもひょっとして既存のものがあるかも？というか、[これ](https://www.wikidata.org/wiki/Wikidata:EveryPolitician)がズバリそう？

**Comment by koujikozaki** [comment]
情報をありがとうございます．

popolo から wikidata id を参照の書き方は，これを使えばOKですね．

ここで上げてくだされたプロジェクトは，Wikidataでの政治家情報の書き方を議論しているので，このプロジェクトで上げているプロパティを使えばよさそうですね．
popolo とのマッピング自体は，明記されていませんが，確かに探せば誰かやってそう．

**Comment by koujikozaki** [comment]
とりあえず，
https://github.com/everypolitician
にいろいろWikidataの政治家情報を扱うツールがある模様．

ただ，今回使うプロパティを決めれば，SPARQL使って自前で簡単なものを用意するほうが楽かも．

**Comment by koujikozaki** [comment]
以下，東さんの発言より転載
----
Personクラスのpopolo<->Wikidata対応をまとめてみました。こんな感じで良いでしょうか。
https://docs.google.com/spreadsheets/d/14s77FAaOitw2le1d049DwCpCUI3Dsu7pD8yA6-rfjRI/edit?usp=sharing
他は本日中くらいにはできると思います。
----
ひとつだけ、「biography」というtermは政治家の略歴みたいなモノを指すんだと思いますが、Wikidataではまだそういうあいまいな集団項目が定義されていないのでひとまずWikidataに対応するWikipadia記事に紐付けてあります。もしかしたら「職業」プロパティや「出身校」プロパティを列挙すれば良いのかもしれませんが。

**Comment by hkwi** [comment]
https://www.wikidata.org/wiki/Wikidata:EveryPolitician/Report:P1313/P39
wikidata と everypolitician 連携しているというのは、例えばこんなのが出てるということなのですね。なるほどー面白い。
下のほうに SPARQL も載ってます。

**Comment by hkwi** [comment]
biography は popolo 仕様的にはテキストが値で、popolo-RDF では [bio:biography](http://vocab.org/bio/#biography) にマッピングされて値は「literal formatted with HTML markup or a pointer to an HTML document」だそうです。
wikidata とは直接マッピングできないかも…なので、popolo 仕様に拡張を入れて使うか、LOD 的に連結できるように popolo-RDF の横に置くのがいいかもしれないです。検討しないとですね。

**Comment by hkwi** [comment]
選挙とは一旦切り離して、衆議院議員一覧という意味では、[wikidata 上](https://www.wikidata.org/wiki/Wikidata:EveryPolitician) の "Dated Memberships" が正しい値になるように整備するのは、それはそれで有意義に思えます。（"Current Membership"＝現在 0 になるのが正しい）

**Comment by koujikozaki** [comment]
>wikidata 上 の "Dated Memberships" が正しい値になるように整備する
ですが，現状のWikidataでは「役職」が「衆議院議員」とだけ書いてあって，「在任期間（開始日，終了日）」がほとんど書いていません．
仕組みとしては書けるので，その辺をうまく分担して行えると良いのですが．．．

ちなみに，同じ問題は「○○大臣」や「○○知事」，「所属政党」などについても言えます．
現状の政治家情報のAPIでは，そこまでのデータが整備されていない（現職しか取れない）ような感じなので，「Wikidataとのマッピング」の意義として，このような点を注力するのは，1つの方向性としてありと思います．

**Comment by halsk** [comment]
mySociety 側からデータ形式のSpreadsheetが来ました。

This is a quick spreadsheet with the fields of the data we are looking to collect (we have various tools available to help with some of the Wikidata elements as well). We can talk through the details on the call.

https://docs.google.com/a/mysociety.org/spreadsheets/d/1QwRm2vN9uDSOt7Vw8BhgX0AP-KQ85pe-tLyaMBJynpQ/edit?usp=sharing

質問事項があれば、 #14 にコメントください
